% Image denoising using kernel PCA. 
%
% make_noisy_data    - Adds Gaussian noise to USPS database.   
% show_denois_tuning - Plots curves of tuning stage of Kernel PCA.
% show_denoising     - Image denosing of USPS hand-written numerals.
% train_kpca_denois  - Training of kernel PCA model for image denoising.  
% train_lin_denois   - Training of linear PCA model for image denoising.
%
% USPSModelGreedyKPCA.mat - Kernel PCA model of USPS numerals.
% USPSModelLinPCA.mat     - Linear PCA model of USPS numerals.
% noisy_circle.mat        - Toy data generated by 'gencircledata'.
%

% About: Statistical Pattern Recognition Toolbox
% (C) 1999-2004, Written by Vojtech Franc and Vaclav Hlavac
% <a href="http://www.cvut.cz">Czech Technical University Prague</a>
% <a href="http://www.feld.cvut.cz">Faculty of Electrical Engineering</a>
% <a href="http://cmp.felk.cvut.cz">Center for Machine Perception</a>

% Modifications:
% 10-jun-2004, VF
